services:
  flowellaapi:
    image: flowellaapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=${WEB_DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    command: /bin/sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_SERVER: ${DATABASE_SERVER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:


